services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-pos
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123++"

    volumes:
      - sqlserver_data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Admin123++' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: PosApi/src/PosApi/Dockerfile

    container_name: pos-backend
    restart: unless-stopped
    
    volumes:
      - ./uploads/images:/app/wwwroot/images

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5227"

      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PosDb;User Id=sa;Password=Admin123++;TrustServerCertificate=True;MultipleActiveResultSets=True;"

      Jwt__Key: "ESTA_ES_UNA_CLAVE_SUPER_SECRETA_DE_MINIMO_32_CARACTERES"
      Jwt__Issuer: "PosApi"
      Jwt__Audience: "PosClient"
      Jwt__ExpirationHours: "8"

    expose:
      - "5227"

  frontend:
    build:
      context: ./pos-client
      dockerfile: Dockerfile

    container_name: pos-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  sqlserver_data:
